name: dart_pbx
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dart_sip_parser:
    git:
      url: https://github.com/Kellykinyama12/dart-sip-parser.git
      ref: main # branch name
  dotenv: ^4.2.0
  intl: ^0.19.0
  logger: ^2.1.0
  parser_error: ^0.2.0
  random_string: ^2.3.1
  recase: ^4.1.0
  sdp_transform: ^0.3.2
  uuid: ^4.3.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
